project:
  type: website
  output-dir: docs

website:
  site-url: https://lulliter.github.io/osservatorio/
  title: "Osservatorio Dati Sociali"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: questions.qmd
        text: Domande e approfondimenti
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    toc-location: left
    lang: it
    embed-resources: true
